#!/usr/bin/env node
// generate-config.js
// Reads .env and generates config.js for the Chrome extension.
// Run: node generate-config.js
//
// config.js is gitignored — always generate it from .env, never edit it directly.

const fs = require('fs');
const path = require('path');

// --- Read .env ---
const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  console.error('❌ .env file not found. Copy .env.example to .env and fill in your keys.');
  process.exit(1);
}

const env = {};
fs.readFileSync(envPath, 'utf8')
  .split('\n')
  .forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const [key, ...rest] = trimmed.split('=');
    if (key) env[key.trim()] = rest.join('=').trim();
  });

// --- Validate required keys ---
const required = ['DEEPGRAM_API_KEY', 'GEMINI_API_KEY'];
const missing = required.filter(k => !env[k] || env[k].includes('your_'));
if (missing.length) {
  console.error(`❌ Missing or placeholder keys in .env: ${missing.join(', ')}`);
  process.exit(1);
}

// --- Generate config.js ---
const configContent = `// config.js — AUTO-GENERATED from .env by generate-config.js
// Do NOT edit this file directly. Edit .env and re-run: node generate-config.js
// This file is gitignored.

const CONFIG = {
  DEEPGRAM_API_KEY: "${env.DEEPGRAM_API_KEY}",
  GEMINI_API_KEY: "${env.GEMINI_API_KEY}",

  // Deepgram WebSocket parameters (tuned per research/PITFALLS.md)
  DEEPGRAM_WS_URL: "wss://api.deepgram.com/v1/listen",
  DEEPGRAM_PARAMS: {
    model: "nova-3",
    utterance_end_ms: 1000,
    endpointing: 500,
    encoding: "linear16",
    sample_rate: 16000,
  },

  // Gemini model
  GEMINI_MODEL: "gemini-3.1-flash-lite-preview",
};
`;

const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');
console.log('✅ config.js generated from .env');
console.log(`   DEEPGRAM_API_KEY: ${env.DEEPGRAM_API_KEY.slice(0, 8)}...`);
console.log(`   GEMINI_API_KEY:   ${env.GEMINI_API_KEY.slice(0, 8)}...`);
console.log(`   GEMINI_MODEL:     gemini-3.1-flash-lite-preview`);
